---
 - name   : Copy DB from Prom to QA
   hosts  : df_prom_db01
   become : yes
   gather_facts: True
   
      tasks:
    - name  : Get date
      shell : echo {{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}
      register : date
 - name: Stop IIS df-qa-web01
   hosts  : win_servers_qa
   tasks:
    - name: test WinRM
      win_shell: D:\STOP_IIS_DOMS.ps1
 - name   : Restore DB from dump
   hosts  : df_qa_db01
   become : yes
   gather_facts: True

   tasks:
    - name  : Drop n create DB ffoms_demo
      shell : psql -f /u01/drop_n_create_db.sql
      become_user : postgres

    - name  : Create extensions on DB ffoms_demo
      shell : psql -f /u01/create_extensions.sql ffoms_demo
      become_user : postgres

    - name  : Get name of new dump
      shell : cat /u01/postgres/backup_name
#        cd /u01/postgres/ 
#        ls | grep {{ ansible_date_time.date }}_{{ ansible_date_time.hour }}
      register: dump
      become_user : postgres

    - name  : Change own
      shell : chown postgres:postgres /u01/postgres/{{ dump.stdout}}

    - name  : Restore dump file
      shell: pg_restore -d ffoms_demo /u01/postgres/{{ dump.stdout}} >/u01/postgres/restore_ffoms_demo_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}.txt 2>&1
      become_user : postgres

 - name: Start IIS df-qa-web01
   hosts  : win_servers_qa
   tasks:
    - name: test WinRM
      win_shell: D:\START_IIS_DOMS.ps1

 - name   : END
   hosts  : df_qa_db01
   become : yes
   
   tasks:
    - name  : END
      shell : cat /u01/end_file

